CREATE TABLE  "STUD_LOG" 

   (	"ROLLNO" NUMBER(4,0), 
	"STUDENTNAME" VARCHAR2(20) NOT NULL, 
	"STANDARD" VARCHAR2(2) NOT NULL, 
	"DOB" DATE, 
	"FEES" NUMBER(9,2), 
	"LEAVE_DATE" DATE, 
	 PRIMARY KEY ("ROLLNO")
   ) ;
